steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['clean']

- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest', '.']
images: ['europe-west1-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest']
options:
  logging: CLOUD_LOGGING_ONLY