steps:
- id: maven-clean
  name: 'gcr.io/cloud-builders/mvn:3.9.1'
  args: ['clean']

- id: maven-package
  name:  'gcr.io/cloud-builders/mvn:3.9.1'
  args: ['package','-Dmaven.test.skip=true']

- id: docker-build-and-push
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest', '.']
images: ['europe-west1-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest']
options:
  logging: CLOUD_LOGGING_ONLY

- id: deploy-to-k8s
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s.yaml
  - --location=europe-west1
  - --cluster=final-task