steps:
# Pull the latest version of gcr.io/cloud-builders/mvn
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8']

# Build the maven project, omitting the docker build step
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['-B', '-P-local-docker-build', 'clean', 'install']
  id: 'MAVEN'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest', '.']
images: ['europe-central2-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest']
options:
  logging: CLOUD_LOGGING_ONLY