steps:
# Pull the latest version of gcr.io/cloud-builders/mvn
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8']

# Build the maven project, omitting the docker build step
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['-B', '-P-local-docker-build', 'clean', 'install']
  id: 'MAVEN'

# Execute the docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=${_IMAGE}', '--no-cache', 'java-runtime-builder-docker/target/classes/docker']
  id: 'DOCKER'

images: ['${_IMAGE}']