apiVersion: apps/v1
kind: Service
metadata:
  name: app-svc
spec:
  type: LodeBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app-container
        image: europe-west1-docker.pkg.dev/$PROJECT_ID/final-task/final-task:latest
