apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serivce-account

---
apiVersion: apps/v1
kind: Service
metadata:
  name: app-service
spec:
  type: LodeBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      serviceAccountName: app-serivce-account
      containers:
      - name: sample-app-container
        image: europe-west1-docker.pkg.dev/cloud-x-432119/final-task/final-task:latest
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "--private-ip"
          - "--structured-logs"
          - "--port=5432"
          - "test-db"
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"
